language: node_js

node_js:
  - 8.9.3

cache:
  directories:
    - node_modules

script:
  - npm run lint

deploy:
  - app:
      master: onigiri-api
    api_key:
      secure: $HEROKU_API_KEY
    provider: heroku

notifications:
  email:
    on_failure: always
    on_success: change
